<?php

/**
 * @file
 * Hook implementations for Exhibit Components module.
 */

use Drupal\image\Entity\ImageStyle;
use Drupal\image\Plugin\Field\FieldType\ImageItem;

/**
 * Implements hook_library_info_alter().
 */
function exhibit_components_library_info_alter(&$libraries, $module) {
  if ($module === 'exhibit_components') {
    // Prefer local libraries over CDN when possible.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = Drupal::service('library.libraries_directory_file_finder');
    $uikit_js = $library_file_finder->find('uikit/dist/js/uikit.min.js');
    $uikit_css = $library_file_finder->find('uikit/dist/css/uikit.min.css');
    if ($uikit_js && $uikit_css) {
      unset($libraries['uikit']['js']);
      // Stash the overrides we have in uikit/css/theme.
      $uikit_css_overrides = $libraries['uikit']['css']['theme'];
      unset($libraries['uikit']['css']);
      unset($libraries['uikit']['version']);
      $libraries['uikit']['js']['/' . $uikit_js] = ['minified' => TRUE];
      $libraries['uikit']['css']['component']['/' . $uikit_css] = ['minified' => TRUE];
      // Include the overrides we have.
      $libraries['uikit']['css']['theme'] = $uikit_css_overrides;
    }
  }
}

/**
 * Implements hook_theme().
 */
function exhibit_components_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__uikit_full_html' => [
      'template' => 'paragraph--uikit-full-html',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_grid' => [
      'template' => 'paragraph--uikit-grid',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_heading' => [
      'template' => 'paragraph--uikit-heading',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_slideshow' => [
      'template' => 'paragraph--uikit-slideshow',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_quote' => [
      'template' => 'paragraph--uikit-quote',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_image_text_display' => [
      'template' => 'paragraph--uikit-image-text-display',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_nav' => [
      'template' => 'paragraph--uikit-nav',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_card' => [
      'template' => 'paragraph--uikit-card',
      'base hook' => 'paragraph',
    ],
    'node__exhibit' => [
      'template' => 'node--exhibit',
      'base hook' => 'node',
    ],
    'node__islandora_object__entity_embed' => [
      'template' => 'node--islandora-object--entity-embed',
      'base hook' => 'node',
    ],
    'node__exhibit__card' => [
      'template' => 'node--exhibit--card',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_node__BUNDLE().
 */
function exhibit_components_preprocess_node__exhibit(&$variables) : void {
  $banner_image_field = $variables['content']['field_banner_image'] ?? [];
  $banner_image_vars = _exhibit_components_get_image_uri_and_alt($banner_image_field);
  $variables['banner_image_uri'] = $banner_image_vars['uri'];
  $variables['banner_image_alt'] = $banner_image_vars['alt'];
}

/**
 * Helper to get uri and alt from media reference field in preprocessing.
 *
 * @param array $image_item
 *   An array from content in preprocess variables, for a field using the
 *   media_thumbnail display formatter.
 * @return array
 *   An array with a 'uri' key and an 'alt' key. Populated if expected values
 *   exist, or empty strings if values cannot be found for the given field.
 */
function _exhibit_components_get_image_uri_and_alt(array $media_thumb_field) : array
{
  $to_return = [
    'uri' => '',
    'alt' => '',
  ];

  $image = $media_thumb_field[0] ?? [];
  $image_formatter = $media_thumb_field['#formatter'] ?? '';
  if (!empty($image) && ($image_formatter === 'media_thumbnail')) {
    /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem */
    $item = $image['#item'];
    if (($entity = $item->entity) && empty($item->uri)) {
      $file_uri = $entity->getFileUri();
      $image_style = $image['#image_style'];
      $image_uri = ImageStyle::load($image_style)?->buildUrl($file_uri) ?? $file_uri;
    } else {
      $image_uri = $item->uri;
    }
    $to_return['uri'] = $image_uri;
    $to_return['alt'] = $item->alt;
  }

  return $to_return;
}
