<?php

/**
 * @file
 * Hook implementations for Exhibit Components module.
 */

/**
 * Implements hook_library_info_alter().
 */
function exhibit_components_library_info_alter(&$libraries, $module) {
  if ($module === 'exhibit_components') {
    // Prefer local libraries over CDN when possible.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = Drupal::service('library.libraries_directory_file_finder');
    $uikit_js = $library_file_finder->find('uikit/dist/js/uikit.min.js');
    $uikit_css = $library_file_finder->find('uikit/dist/css/uikit.min.css');
    if ($uikit_js && $uikit_css) {
      unset($libraries['uikit']['js']);
      unset($libraries['uikit']['css']);
      unset($libraries['uikit']['version']);
      $libraries['uikit']['js']['/' . $uikit_js] = ['minified' => TRUE];
      $libraries['uikit']['css']['component']['/' . $uikit_css] = ['minified' => TRUE];
    }
  }
}
