<?php

/**
 * @file
 * Hook implementations for Exhibit Components module.
 */

/**
 * Implements hook_library_info_alter().
 */
function exhibit_components_library_info_alter(&$libraries, $module) {
  if ($module === 'exhibit_components') {
    // Prefer local libraries over CDN when possible.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = Drupal::service('library.libraries_directory_file_finder');
    $uikit_js = $library_file_finder->find('uikit/dist/js/uikit.min.js');
    $uikit_css = $library_file_finder->find('uikit/dist/css/uikit.min.css');
    if ($uikit_js && $uikit_css) {
      unset($libraries['uikit']['js']);
      // Stash the overrides we have in uikit/css/theme.
      $uikit_css_overrides = $libraries['uikit']['css']['theme'];
      unset($libraries['uikit']['css']);
      unset($libraries['uikit']['version']);
      $libraries['uikit']['js']['/' . $uikit_js] = ['minified' => TRUE];
      $libraries['uikit']['css']['component']['/' . $uikit_css] = ['minified' => TRUE];
      // Include the overrides we have.
      $libraries['uikit']['css']['theme'] = $uikit_css_overrides;
    }
  }
}

/**
 * Implements hook_theme().
 */
function exhibit_components_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__uikit_full_html' => [
      'template' => 'paragraph--uikit-full-html',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_grid' => [
      'template' => 'paragraph--uikit-grid',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_heading' => [
      'template' => 'paragraph--uikit-heading',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_slideshow' => [
      'template' => 'paragraph--uikit-slideshow',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_quote' => [
      'template' => 'paragraph--uikit-quote',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_image_text_display' => [
      'template' => 'paragraph--uikit-image-text-display',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_nav' => [
      'template' => 'paragraph--uikit-nav',
      'base hook' => 'paragraph',
    ],
    'paragraph__uikit_card' => [
      'template' => 'paragraph--uikit-card',
      'base hook' => 'paragraph',
    ],
    'node__exhibit' => [
      'template' => 'node--exhibit',
      'base hook' => 'node',
    ],
    'node__islandora_object__entity_embed' => [
      'template' => 'node--islandora-object--entity-embed',
      'base hook' => 'node',
    ],
    'node__exhibit__card' => [
      'template' => 'node--exhibit--card',
      'base hook' => 'node',
    ],
  ];
}
